In [4]:
1+3, 1*3, 2-1,3/2,3//3,3**3

(4, 3, 1, 1.5, 1, 27)

In [6]:
# 논리연산자\
# 여러줄 주석 '''''',"""""" 번거로우므로 보통 홀따옴표를 사용

# &&
# ||


In [8]:
# 조건문, 보통 소괄호 없이 사용합니다.
if (5 > 3) :
    print('5>3')
if 5 > 3 :
    print('5>3')

5>3
5>3


In [9]:
# 반복문 기존 : 3항 연산자 반복문이 없다!!!
# for (int i=0; i< 3 ;i++){}
for i in range(3): # 향상된 for문이라고 불리던 반복문
    print(i)

0
1
2


In [96]:
# for 지정된 횟수만큼 반복 while 조건을 만족할때까지 반복
import random
# 0~1 랜덤값을 생성하는데 0.1보다 작은 값을 얻겠다.
while(True):
    v = random.random()
    print(v)
    if v < 0.1:
        break

0.8589123413484129
0.48264030262749424
0.9199205033764084
0.4852719873930528
0.847289514428336
0.7494313276051404
0.8521716393601392
0.5103781857666003
0.9684886715858403
0.34182269274490196
0.2970204762383113
0.14275261892177216
0.22348632712424932
0.7916835248568233
0.5617084224541339
0.6054253127333267
0.6438423443078353
0.09770141901243556


In [101]:
# 함수
'''
기존
int add(int a, int b){
    return a+b;
}

string add(string a, string b){
    return string.format('{0}{1}',a,b);
}

'''
 # 셀 하나에 함수를 정의하는 것이 깨끗합니다.
def add(a,b):
    return a+b

In [103]:
add(1,3),add(1.5,3.3), add('abc','123')

(4, 4.8, 'abc123')

In [149]:
# 클래스, 셀 하나에 정의하세요
class Lotto:
    def __init__(self,k): #생성자
        nums = [] # 지역변수(함수 실행 완료되면 사라집니다)
        self.nums = [] # 클래스변수 ( 클래스가 제거되기 전까지 남습니다)
        for i in range(k):
            self.nums.append(random.randint(1,45))
        print(self.nums)
    
        

In [146]:
# 클래스, 셀 하나에 정의하세요
class Lotto:
    def __init__(self,k): #생성자
        nums = [] # 지역변수(함수 실행 완료되면 사라집니다)
     #   self.nums = [] # 클래스변수 ( 클래스가 제거되기 전까지 남습니다)
        for i in range(k):
            nums.append(random.randint(1,45))
        print(nums)
    
        

In [150]:
lotto1 = Lotto(3)
lotto2 = Lotto(5)

[31, 40, 21]
[34, 24, 45, 31, 20]


In [152]:
lotto1.nums

[31, 40, 21]

In [156]:
d = {'age':30, 'city':'Seoul'}
I = [10, 'a', 'city', [1,2,3]]
t = (10,'a','city',[1,2,3])
d, I, t

({'age': 30, 'city': 'Seoul'},
 [10, 'a', 'city', [1, 2, 3]],
 (10, 'a', 'city', [1, 2, 3]))

In [160]:
# 인덱스, 인덱싱
I[0], I[-1], I[1:3]

# [시작 위치 : 끝 위치(전까지)] 

(10, [1, 2, 3], ['a', 'city'])

In [163]:
[1,2,3,] + [4,5,6]
(1,2,3,) + (4,5,6,)

(1, 2, 3, 4, 5, 6)

In [232]:
import numpy as np

List, Dict, Set 연산용으로 사용이 불가능, 메모리 사용량이 크고 느립니다

In [184]:
numpy.arange(1,10), numpy.arange(1,10,2)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [199]:
# np.array([1,2,3])+ np.array([4,5,6])
numpy.array([1,2,3]) + numpy.array([4,5,6])


array([5, 7, 9])

야후 파이낸스의 SP500 주식 데이터를 읽습니다
csv 혹은 pandas 로 읽을 수 있습니다.

In [200]:
import pandas

In [205]:
stock = pandas.read_csv('^GSPC.csv')
stock.shape # 20행, 7열

(20, 7)

In [210]:

arr = numpy.array(stock)
arr.shape

(20, 7)

In [212]:
arr

array([['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
        2840.22998, 3288870000],
       ['2019-05-21', 2854.02002, 2868.8798829999996, 2854.02002,
        2864.360107, 2864.360107, 3218700000],
       ['2019-05-22', 2856.060059, 2865.469971, 2851.110107, 2856.27002,
        2856.27002, 3192510000],
       ['2019-05-23', 2836.699951, 2836.699951, 2805.48999, 2822.23999,
        2822.23999, 3891980000],
       ['2019-05-24', 2832.409912, 2841.360107, 2820.189941, 2826.060059,
        2826.060059, 2887390000],
       ['2019-05-28', 2830.030029, 2840.51001, 2801.580078, 2802.389893,
        2802.389893, 4121410000],
       ['2019-05-29', 2790.25, 2792.030029, 2766.060059, 2783.02002,
        2783.02002, 3700050000],
       ['2019-05-30', 2786.939941, 2799.0, 2776.73999, 2788.860107,
        2788.860107, 3273790000],
       ['2019-05-31', 2766.149902, 2768.97998, 2750.52002, 2752.060059,
        2752.060059, 3981020000],
       ['2019-06-03', 2751.530029, 2763.07006

In [214]:
arr[0]

array(['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
       2840.22998, 3288870000], dtype=object)

In [216]:
arr[0,0], arr[-1,-1]

('2019-05-20', 1579314342)

In [221]:
arr[0]==arr[0,:]

array([ True,  True,  True,  True,  True,  True,  True])

In [225]:
# Open 만 가져오자
# Data->Open ->High ->Low ->Close ->adj Close ->Volume

o = arr[:,1]
o


array([2841.939941, 2854.02002, 2856.060059, 2836.699951, 2832.409912,
       2830.030029, 2790.25, 2786.939941, 2766.149902, 2751.530029,
       2762.639893, 2818.090088, 2828.51001, 2852.8701170000004,
       2885.830078, 2903.27002, 2882.72998, 2886.23999, 2886.820068,
       2889.75], dtype=object)

In [227]:
# Close 만 가져오자
# Data Open High Low Close adj Close Volume

close = arr[:,4] #도 가능하지만
close = arr[:, -3] # 이 편합니다.
close

array([2840.22998, 2864.360107, 2856.27002, 2822.23999, 2826.060059,
       2802.389893, 2783.02002, 2788.860107, 2752.060059, 2744.449951,
       2803.27002, 2826.149902, 2843.48999, 2873.340088, 2886.72998,
       2885.719971, 2879.840088, 2891.639893, 2886.97998, 2889.669922],
      dtype=object)

In [251]:
# Open -> High -> Low -> Close 4개 컬럼만 뽑자
# [시작:끝]
v4 = arr[:,1:5]
v4.shape

(20, 4)

축 : axis
2차원 데이터는 2개의 축이 있습니다. 행축, 열축

In [254]:
np.max(v4,axis=0)

array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object)

In [244]:
# b(below) 아래쪾에 셀 만들기
# 내장 함수 : import 없이 바로 사용 가능한 함수
max(o), min(o), np.max(o),np.min(o), np.mean(o),np.median(o),np.std(o)

(2903.27002,
 2751.530029,
 2903.27002,
 2751.530029,
 2837.1390014000003,
 2839.319946,
 45.016996538592394)

In [312]:
np.max(o), np.argmax(o)

(2903.27002, 15)

주가가 가장 많이 상승한 날짜를 찾아보세요( 정답 : X 번째 행입니다 )

In [311]:
day = arr[:,0]
close_v = arr[:,-3]
open_v = arr[:,1]
max_v = close_v - open_v

np.max(max_v), np.argmax(max_v), day[np.argmax(max_v)]

(40.6301269999999, 10, '2019-06-04')

### 데이터 분석
 
 - 가격 상승하는 날 거래량이 많아질까?
 - 전날 가격이 상승하면 다음날 시작가경은 더 높은 가경에서 시작할까?
 - 가격 변동이 크면 거래량도 많아질까?
 

### 다음단계 : 예측
 - 어제/오늘 현황 분석이 끝났는데 내일은 Poen/Close 이 어떻게 될까?
 - 방법 : 1. 통계정(R) 2. 머신러닝

- 가격이 상승한 횟수, 가격이 하락한 횟수


In [283]:
 # 가격 상승하는 날 거래량이 많아질까?
 # 전날 가격이 상승하면 다음날 시작가격은 더 높은 가격에서 시작할까?
 # 가격 변동이 크면 거래량도 많아질까?

close_v = arr[:,-3]
open_v = arr[:,1]
vol = arr[:,-1]
gap = close_v - open_v


In [307]:
# 상승한 날의 거래량의 평균
np.mean(vol[gap > 0]),np.mean(vol[gap < 0])

(3286227000.0, 3397639434.2)

In [309]:
# 상승한 날의 거래량이 더 많냐?
np.mean(vol[gap > 0]) > np.mean(vol[gap < 0])

False

In [300]:
# 조건부 검색
a = np.array([1,2,3,4])
even = a%2==0 # 짝수값만 뽑고 싶다
even # 불린 마스크

array([False,  True, False,  True])

In [313]:
# 불린 마스크를 인덱스로 사용하면 True값 만 뽑힙니다
a[even]

array([2, 4])

In [344]:
a= np. array([1,2,3])

In [337]:
a, a.dtype,a.shape

(array([1, 2, 3]), dtype('int32'), (3,))

In [359]:
np.ones((2,3,4), dtype=np.int32,)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [360]:
np.full((2,3,4), 3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [345]:
np.ones((3,2,4), dtype=np.int32,)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [350]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [353]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [361]:
np.linspace(1,10,5) # 시작값, 끝값, x 등분

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [363]:
import random
random.randint(1,10)

10

In [375]:
np.random.rand(2,3) # [0,1]

array([[0.20931666, 0.47384746, 0.97634248],
       [0.39771225, 0.12753834, 0.48663185]])

In [425]:
np.random.normal(size=(2,3))

array([[-0.24915468, -2.88760965,  0.08984177],
       [-0.23048634,  1.06896044, -0.14316112]])

In [428]:
np.random.randint(low=1, high=10, size=(2,3))

array([[4, 9, 9],
       [8, 2, 9]])

In [430]:
np.random.uniform(size=(2,3))

array([[0.45860628, 0.9115292 , 0.24559655],
       [0.70654228, 0.82328585, 0.83241498]])

In [445]:
a = np.ones(shape=(3,5), dtype=np.int)
b = np.ones(shape=(3,1), dtype=np.float) # broadcasting
a + b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [449]:
a=np.arange(6)

In [453]:
b= a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [457]:
b.ndim, b.shape,b.size,b.dtype,b.nbytes

(2, (2, 3), 6, dtype('int32'), 24)

In [460]:
b.flatten()

array([0, 1, 2, 3, 4, 5])

In [461]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [470]:
a =np.array([[0,1,2],
      [3,4,5],
      [6,7,8]])

In [500]:
a[:,1]
a[2:,]
a[:,-2:].flatten()
a[1:,1:].flatten()

array([4, 5, 7, 8])

In [506]:
b=np.array([[0,1,2,3],
      [4,5,6,7],
      [8,9,10,11]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


[5,6,9,10]
[9,10,11]

In [510]:
b[1:,1:3].flatten()
b[2,1:]


array([ 9, 10, 11])

In [515]:
# 3차원
c = np.arange(2*3*4).reshape((2,3,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [533]:
c[0,0],c[1,0],c[0,:,1],c[1,:,-1]

(array([0, 1, 2, 3]),
 array([12, 13, 14, 15]),
 array([1, 5, 9]),
 array([15, 19, 23]))

In [545]:
c[0,1:,2], c[1,1,1:], c[1,:-1,1:3].flatten()

(array([ 6, 10]), array([17, 18, 19]), array([13, 14, 17, 18]))

In [550]:
c.shape
c.reshape(6,4), np.reshape(c,(6,4)) # 편한대로 사용

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [589]:
c.reshape((2,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [601]:
c.size, c.reshape((-1,4))

(24, array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [607]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a,b


(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [638]:
c= np.concatenate((a,b,a), axis=1)
c

array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2],
       [ 3,  4,  5,  9, 10, 11,  3,  4,  5]])

In [640]:
c.shape

(2, 9)

In [642]:
a.shape, b.shape

((2, 3), (2, 3))

In [808]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [809]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [810]:
a
c=np.stack((a,b), axis=2)
c

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [811]:
a.shape, b.shape, c.shape

((2, 3), (2, 3), (2, 3, 2))

In [812]:
kor = [80, 90, 99]
eng = [70, 50, 60]
score = np.stack((kor, eng), axis=1)
score

array([[80, 70],
       [90, 50],
       [99, 60]])

In [813]:
math = np.array([20,30,40]).reshape(3,1)
math

array([[20],
       [30],
       [40]])

In [814]:
kor=score[:,0].reshape(3,1)
eng=score[:,1].reshape(3,1)
kor
eng
k_e_m=np.concatenate((kor,eng,math),axis=1)
score_4=np.array([20,30,40]).reshape(1,3)
k_e_m
k_e_m.shape


(3, 3)

In [815]:
score = np.concatenate((k_e_m,score_4),axis=0)

In [816]:
np.stack((kor,eng,math),axis=0)

array([[[80],
        [90],
        [99]],

       [[70],
        [50],
        [60]],

       [[20],
        [30],
        [40]]])

In [817]:
# 각 과목별 평균은?
# 시험을 가장 잘 본 학생의 평균 점수는?

print('과목평균',np.average(score,axis=0))
print('시험 가장 잘본 학생 평균',np.average(score,axis=1))
np.max(np.mean(score,axis=1))

과목평균 [72.25 52.5  32.5 ]
시험 가장 잘본 학생 평균 [56.66666667 56.66666667 66.33333333 30.        ]


66.33333333333333

In [837]:
np.savetxt('kkk.txt',score,fmt='%d')

In [845]:
s = np.loadtxt('kkk.txt')
s


array([[80., 70., 20.],
       [90., 50., 30.],
       [99., 60., 40.],
       [20., 30., 40.]])

In [861]:
s[:,::-1] # 시작부터 끝까지 거꾸로

array([[20., 70., 80.],
       [30., 50., 90.],
       [40., 60., 99.],
       [40., 30., 20.]])

In [850]:
s[:,::2] #시작부터 끝까지 스텝(간격) 2

array([[80., 20.],
       [90., 30.],
       [99., 40.],
       [20., 40.]])

In [854]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [862]:
# [시작:끝:간격] 생략하면 기본값 시작=처음부터, 끝:끝, 간격:1
a[::2], a[1::2],a[1::3], a[2:6:2]

(array([0, 2, 4, 6, 8]),
 array([1, 3, 5, 7, 9]),
 array([1, 4, 7]),
 array([2, 4]))

In [880]:
np.split(a,[3,6])
np.split(a,[1,7]) # 해당 위치를 잘라라

[array([0]), array([1, 2, 3, 4, 5, 6]), array([7, 8, 9])]

In [897]:
# 분리하기 section 갯수
# 머신러닝에서 데이터 셋을 k개 분리해서 k-fold validationset 을 만듭니다.
# k=3 이라면, 데이터를 3개로 분리해서 2개 셋을 학습, 1개 셋은 테스트로 사용

'''
3-ford validation set
ABC

학습 : AB   테스트 : C
학습 : BC   테스트 : A
학습 : AC   테스트 : B

'''
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [913]:
np.arange(12).reshape(4,3)
a * 2
a.shape
a*2
a
a = np.array([0,10,20,30])
a = np.stack((a,a,a),1)
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [922]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [918]:
a.shape, b.shape

((4, 3), (3,))

In [923]:
a + b


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [968]:
d = np.array([0,10,20,30]).reshape(4,1)
e = np.array([0,1,2,3,4,5]).reshape(1,6)
d + e

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [970]:
7 == 3

False

In [973]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [975]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [985]:
a = np.arange(8)
b = np.arange(1,3)
a
b

array([1, 2])

In [986]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [993]:
mask = a > 2

In [995]:
mask

array([False, False, False,  True,  True,  True,  True,  True])

In [989]:
a[mask]

array([3, 4, 5, 6, 7])

In [991]:
np.logical_not(mask)

array([ True,  True,  True, False, False, False, False, False])

In [996]:
np.logical_and(mask,mask)

array([False, False, False,  True,  True,  True,  True,  True])

In [998]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [1002]:
mask0 = a % 2 == 0
mask1 = a > 2
mask0, mask1

(array([ True, False,  True, False,  True, False,  True, False]),
 array([False, False, False,  True,  True,  True,  True,  True]))

In [1004]:
np.logical_and(mask0, mask1)

array([False, False, False, False,  True, False,  True, False])

In [1006]:
a[mask]

array([3, 4, 5, 6, 7])

In [1010]:
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

주식 데이터 2개를 받아서 concatenate 로 붙이세요
df = pandas.read_csv()로 파일 읽고
arr0 = np.array(df[]) 필요한 숫자 부분만
arr = np.concatenate((arr0, arr1), axis=0)

In [1081]:


stock_2017 = pandas.read_csv('^DJI_2017.csv')
stock_2018 = pandas.read_csv('^DJI_2018.csv')
stock_2017
stock_2018
arr_2017 = np.array(stock_2017)
arr_2018 = np.array(stock_2018)
arr_2017[:,1:]
arr_2018[:,1:]

arr_2017_2018=np.concatenate((arr_2017[:,1:],arr_2018[:,1:]), axis=0)
np.savetxt('arr_2017_2018.csv',arr_2017_2018,fmt='%d')
arr_2017[0]


array(['2017-06-19', 21444.75, 21528.990234, 21436.080078, 21528.990234,
       21528.990234, 289400000], dtype=object)

In [1110]:
np.mean(arr_2017_2018[:,1:], axis=0).astype(np.int)


array([    24927,     24673,     24807,     24807, 324934236])

In [1109]:

Close = arr[:,4]
Open = arr[:,1]
Gap = Close - Open
abs_Gap=np.abs(Gap)
index = np.argmax(abs_Gap)
np.max(Gap), arr[index,0]

(40.6301269999999, '2019-06-04')