### 7장 텍스트 데이터 다루기

In [82]:
import numpy as np

In [83]:
sentencaes = ['토니 스타크가 피터 파커를 얼마나 사랑하는지 알 수 있는 영화 ~ 영화'
            ,'cg 팀은 과로사 직전까지 갔을것이야...']

In [84]:
type(sentences), len(sentences)

(list, 2)

#### BOW(Bag of Words) 단어 가방으로 전처리

In [215]:
#420
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer # 갯구를 세어서 배열로 만든다

In [216]:
vect = CountVectorizer()
vect = TfidfVectorizer()

In [217]:
vect.fit(sentences)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [218]:
len(vect.vocabulary_), vect.vocabulary_  # 등장하는 어휘들

(6, {'안녕': 3, '나는': 0, '남자야': 2, '남자': 1, '여자야': 5, '여자': 4})

In [219]:
#dense_maxtix <-> spase_matrix(자연어) : 메모리 절약하기 위해서 사용
sparse_matrix = vect.transform(sentences) # 자연어를 BOW로 변환
sparse_matrix

<2x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [220]:
sparse_matrix.toarray() # sparse 를 dense 로 변환

array([[0.40993715, 0.57615236, 0.57615236, 0.40993715, 0.        ,
        0.        ],
       [0.40993715, 0.        , 0.        , 0.40993715, 0.57615236,
        0.57615236]])

In [221]:
sentences

['안녕, 나는 남자야 남자!', '안녕, 나는 여자야 여자!!']

In [222]:
from sklearn.datasets import fetch_20newsgroups

In [223]:
news = fetch_20newsgroups()  # Download 진행됩니다.

In [224]:
len(news.data), len(news.target_names), news.target_names

(11314,
 20,
 ['alt.atheism',
  'comp.graphics',
  'comp.os.ms-windows.misc',
  'comp.sys.ibm.pc.hardware',
  'comp.sys.mac.hardware',
  'comp.windows.x',
  'misc.forsale',
  'rec.autos',
  'rec.motorcycles',
  'rec.sport.baseball',
  'rec.sport.hockey',
  'sci.crypt',
  'sci.electronics',
  'sci.med',
  'sci.space',
  'soc.religion.christian',
  'talk.politics.guns',
  'talk.politics.mideast',
  'talk.politics.misc',
  'talk.religion.misc'])

In [225]:
print(news.data[1])

From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>



In [226]:
news.target[1],news.target_names[1]

(4, 'comp.graphics')

In [227]:
len(news.data), len(news.target_names)

(11314, 20)

자연어 뉴스를 배열(vector)로 변환 / BOW

In [228]:
vect = CountVectorizer().fit(news.data) #

In [229]:
len(vect.vocabulary_)

130107

In [230]:
sm = vect.transform(news.data)

In [231]:
sm

<11314x130107 sparse matrix of type '<class 'numpy.int64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [232]:
from sklearn.linear_model import LogisticRegression

In [233]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [234]:
model.score(sm, news.target)

0.999734841788934

In [235]:
test_set = ['Hi, Major League Base Ball, who Is Winner?', 
            'I want to buy a apple, where shoud I go?']

In [236]:
model.predict(vect.transform(test_set))


array([9, 4])

In [237]:
news.target_names[9],news.target_names[4]

('rec.sport.baseball', 'comp.sys.mac.hardware')

In [238]:
sm_test = vect.transform(test_set)
dm = sm_test[0].toarray()
dm.shape

(1, 130107)

In [239]:
np.sum(dm), dm

(8, array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64))

In [240]:
sm_test[0].indices # Indexes 배열의 크기가 너무 크기 때문에 0이 아닌 값이 있는 위치를 볼 수 밖에 없습니다.

array([ 31657,  31951,  63092,  68532,  75022,  79043, 124147, 124501])

In [241]:
import konlpy

In [242]:
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()
pprint(kkma.sentences(u'네, 안녕하세요. 반갑습니다.'))

['네, 안녕하세요.', '반갑습니다.']


In [243]:
pprint(kkma.nouns(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.'))

['질문', '건의', '건의사항', '사항', '깃헙', '이슈', '트래커']


In [244]:
pprint(kkma.pos(u'오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^'))

[('오류', 'NNG'),
 ('보고', 'NNG'),
 ('는', 'JX'),
 ('실행', 'NNG'),
 ('환경', 'NNG'),
 (',', 'SP'),
 ('에러', 'NNG'),
 ('메세지', 'NNG'),
 ('와', 'JKM'),
 ('함께', 'MAG'),
 ('설명', 'NNG'),
 ('을', 'JKO'),
 ('최대한', 'NNG'),
 ('상세히', 'MAG'),
 ('!', 'SF'),
 ('^^', 'EMO')]


In [245]:
#p445
from konlpy.tag import Okt
okt_tag = Okt()
okt_tag.morphs(u'질문이나 건의사항은 깃험 이슈 트래커에 남겨주세요.')

['질문', '이나', '건의', '사항', '은', '깃', '험', '이슈', '트래커', '에', '남겨주세요', '.']

In [151]:
kkma.morphs(u'오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^')

['오류',
 '보고',
 '는',
 '실행',
 '환경',
 ',',
 '에러',
 '메세지',
 '와',
 '함께',
 '설명',
 '을',
 '최대한',
 '상세히',
 '!',
 '^^']

In [246]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) # 문장 -> 벡터로 변환할때 단어 자르는 기능을 konlpy를 사용
cv = TfidfVectorizer(tokenizer=okt_tag.morphs) # 문장 -> 벡터로 변환할때 단어 자르는 기능을 konlpy를 사용

In [247]:
sentences = ['안녕, 나는 남자야 남자!', '안녕, 나는 여자야 여자!!']

In [248]:
cv = cv.fit(sentences) # 토큰(단어)을 다 잘라서 어휘 사전(vocaburary)를 준비합니다.

In [249]:
cv.vocabulary_

{'안녕': 6, ',': 2, '나': 3, '는': 5, '남자': 4, '야': 7, '!': 0, '여자': 8, '!!': 1}

In [250]:
sparse_matrix = cv.transform(sentences) # 문장을 희소 행렬로 벼환

In [251]:
sparse_matrix.toarray()

array([[0.36439074, 0.        , 0.25926702, 0.25926702, 0.72878149,
        0.25926702, 0.25926702, 0.25926702, 0.        ],
       [0.        , 0.36439074, 0.25926702, 0.25926702, 0.        ,
        0.25926702, 0.25926702, 0.25926702, 0.72878149]])

네이버 영화 리뷰 추천/비추천 분류

In [252]:
import pandas as pd

In [253]:
movie = pd.read_csv('ratings_train.txt',delimiter='\t')

In [254]:
movie.shape

(150000, 3)

In [255]:
movie = movie.drop(columns='id')
movie = movie.dropna()

In [256]:
m = 1000
movie = movie.iloc[:m]

In [257]:
movie.head(2)

document  label
0                아 더빙.. 진짜 짜증나네요 목소리      0
1  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1

In [258]:
movie.isna().sum()

document    0
label       0
dtype: int64

In [259]:
X = movie['document']
y = movie.label

In [260]:
from konlpy.tag import Okt
cv = CountVectorizer(tokenizer=Okt().morphs) # 문장 -> 벡터로 변환할때 단어 자르는 기능을 konlpy를 사용

In [261]:
cv = cv.fit(X)

In [262]:
len(cv.vocabulary_)

4767

In [263]:
cv.vocabulary_

{'아': 2638,
 '더빙': 1139,
 '..': 33,
 '진짜': 4042,
 '짜증나네요': 4067,
 '목소리': 1679,
 '흠': 4745,
 '...': 38,
 '포스터': 4396,
 '보고': 1939,
 '초딩': 4165,
 '영화': 3064,
 '줄': 3940,
 '....': 40,
 '오버': 3112,
 '연기': 3021,
 '조차': 3822,
 '가볍지': 275,
 '않구나': 2762,
 '너': 910,
 '무재': 1719,
 '밓었': 1808,
 '다그': 1020,
 '래서': 1403,
 '보는것을': 1955,
 '추천': 4191,
 '한': 4518,
 '다': 1017,
 '교도소': 539,
 '이야기': 3394,
 '구먼': 550,
 '솔직히': 2424,
 '재미': 3619,
 '는': 999,
 '없다': 2934,
 '평점': 4389,
 '조정': 3821,
 '사이': 2230,
 '몬페': 1683,
 '그': 582,
 '의': 3314,
 '익살스런': 3432,
 '가': 256,
 '돋보였던': 1177,
 '!': 0,
 '스파이더맨': 2484,
 '에서': 2972,
 '늙어': 1002,
 '보이기만': 1994,
 '했던': 4612,
 '커스틴': 4232,
 '던스트': 1143,
 '너무나도': 913,
 '이뻐': 3372,
 '보였다': 1991,
 '막': 1481,
 '걸음': 420,
 '마': 1454,
 '뗀': 1356,
 '3': 96,
 '세': 2383,
 '부터': 2101,
 '초등학교': 4164,
 '1': 58,
 '학년': 4513,
 '생인': 2320,
 '8': 114,
 '살용': 2260,
 '.': 27,
 'ㅋㅋㅋ': 228,
 '별': 1929,
 '반개': 1841,
 '도': 1155,
 '아까': 2641,
 '움': 3216,
 '원작': 3241,
 '긴장감': 680,
 '을': 3307,
 '제

In [264]:
X_sm = cv.transform(X)

In [265]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression,RidgeClassifier # classification

In [266]:
scores = cross_val_score(LogisticRegression(), X_sm,y, cv=3)
scores = cross_val_score(RidgeClassifier(), X_sm,y, cv=3)
scores

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.70658683, 0.6996997 , 0.66066066])

In [267]:
model = LogisticRegression().fit(X_sm,y)
model = RidgeClassifier().fit(X_sm,y)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [268]:
문장 = ['스파이더맨 거미 인가 멋있어요 ㅋㅋㅋㅋㅋ','캐스팅 구려요', 
      '최악의 영화','성룡','두번 봐라','재밌게 ']
model.predict(cv.transform(문장))

array([0, 0, 0, 0, 1, 1], dtype=int64)